### ISSUE TITLE
Pale Moon supporting

### ISSUE THREAD

**Issue by Martii** [janekptacijarabaci/greasemonkey#1]
So I've been pondering adding your "Fork" branch along with a Pale Moon to [the docs on OUJS](https://openuserjs.org/about/Userscript-Beginners-HOWTO)... however...

> No, I don't want to fork the project.

... implies heavily that you may drop it at some point.

Without a supporting team for the .user.js engine I am not entirely sure I would want to cement that into the OUJS documentation though.

You know how I work now, more or less, and I usually make every available effort to assist. It was always my goal with GM Port to be reintegrated back into GM upstream however with as many changes that are coming up I'm not sure that's possible long term... and of course some occasional resistance from upstream.

Soooooo the decision is up to you to go official support in whatever manner you deem necessary. Think about this hard as I don't need an answer right away.

OUJS Admin

**Comment by janekptacijarabaci** [comment]
Thank you. Unfortunately, I do not have enough time for that.

See also https://forum.palemoon.org/viewtopic.php?f=16&t=10293

**Comment by Martii** [comment]
Well let me see if I can sneak it into a sub-document then... that probably won't make it look very good for PM though... I'll think about it a bit more... perhaps something like a "Other UserScript Engines" page which could cover Scriptish as well and be a little more simplified for maintaining.

I do appreciate what you do for GM, recently SM, and PM. :)
