### ISSUE TITLE
Making update sticky

### ISSUE THREAD

**Issue by markfilipak** [janekptacijarabaci/greasemonkey#10]
Appologies if this post is in the wrong place... I'm a gm-noob (and github mystifies me).

App: Greasemonkey for Pale Moon 3.30
Browser: Pale Moon 27.7.2 (64-bit)

'about:addons' > 'Available Updates' is prompting me to accept Greasemonkey for Pale Moon 3.31beta2. I don't want to install any beta software because I don't feel competent (yet) to evaluate beta software. But though I remove the 'Include in Update' checkmark, the next time I open 'about:addons' > 'Available Updates' it's once again checked. How do I unselect updating to the 3.31beta2 & make it stick?

Thanks!
Mark.

**Comment by janekptacijarabaci** [comment]
Yes, it's a little confusing. I am aware of this but thanks for the feedback. Starting from the next version (3.31) will no longer use a beta/rc version. And if so, they will not be allowed to auto-upgrade.

**Comment by janekptacijarabaci** [comment]
Version bump: 3.31
