### ISSUE TITLE
Automatic updates setting doesn't seem to be honored

### ISSUE THREAD

**Issue by Martii** [janekptacijarabaci/greasemonkey#11]
I have a script that I installed from GH a while back and the author deleted his repo *(which is disheartening)*. 

I noticed the failure show up in the usual popup box so I turned Automatic Updates to Off for that script... and every browser self-update check *(not forced)* it continues to go there and show me the failure.

System stats:
* `Mozilla/5.0 (X11; Linux x86_64; rv:52.9) Gecko/20100101 Goanna/3.4 Firefox/52.9 PaleMoon/27.9.3`
* Greasemonkey "Fork" 3.31.1

Thanks for the relook.

**Comment by janekptacijarabaci** [comment]
Thank you. It should be fixed in the version ~~3.31.2~~ 3.31.3

**Comment by Martii** [comment]
Seems to be working well in 3.31.3... had to change about:config?filter=extensions.update.interval to something much shorter to test. 

Thank you.

**Comment by janekptacijarabaci** [comment]
@Martii 
> had to change about:config?filter=extensions.update.interval to something much shorter to test

...or e.g. `app.update.lastUpdateTime.addon-background-update-timer` to much lower value, restart the browser and wait for a while :-)
