### ISSUE TITLE
Facebook / F.B. Purity issue on Messenger

### ISSUE THREAD

**Issue by Gittyperson** [janekptacijarabaci/greasemonkey#3]
Many thanks for your version!

Something that's occurring the last few days on Pale Moon 27.1 and latest script version of [F.B. Purity](http://www.fbpurity.com/install.htm). Does not happen when FBP is disabled (Pale Moon) - I've disabled all other extensions, too.
Does not occur on Firefox (with 'official' Greasemonkey) so I can't know where the issue is. 

In the Messenger (its new 'full-screen' version - the bottom message/chat pop-ups work fine) all stickers are hidden. They are sent/received but never appear. Some warnings I get from the error console (don't know if related to this):

```
Warning: Error in parsing value for 'image-rendering'.  Declaration dropped.
Source File: https://www.facebook.com/messages/t/[numbers.here]
Line: 0
Source Code:
-webkit-optimize-contrast
```
and

```
Warning: Error in parsing value for 'width'.  Declaration dropped.
Source File: https://www.facebook.com/messages/t/[numbers.here]
Line: 0
Source Code:
undefinedpx
```

**Comment by janekptacijarabaci** [comment]
I'm sorry, but I cannot repeat this test (either currently or in the foreseeable future).

**Comment by janekptacijarabaci** [comment]
@Gittyperson
I cannot still try, but the script uses "element.innerText"...

You can try the unstable version:
http://www.palemoon.org/unstable/

See:
https://github.com/MoonchildProductions/Pale-Moon/issues/906

See also:
https://forum.palemoon.org/viewtopic.php?f=29&t=14879&p=107493

**Comment by Gittyperson** [comment]
Thanks for the tip. Tried the unstable and GM 3.9.3.1 but problem remains. It's FBP's "Revert Bubble Chat" option that causes/triggers this issue.

**Comment by Gittyperson** [comment]
Closing this since it does happen on Firefox too, I probably had that option disabled on FF and missed it. It does not happen on Edge/Tampermonkey.
