### ISSUE TITLE
Auto Page Reload on Error & Gateway Problem Fixer (script) unsupported

### ISSUE THREAD

**Issue by xevidencex** [janekptacijarabaci/greasemonkey#6]
this script ceased working with your updates:
http://userscripts-mirror.org/scripts/show/112519

you can test it on an unexisting site for ex:
http://www.lolhuyuoh.com/

it should try to reload it, for facing the "problem loading page" case..

**Comment by janekptacijarabaci** [comment]
Thank you for your feedback, but you see:
https://github.com/greasemonkey/greasemonkey/issues/1450
