### ISSUE TITLE
FrankerFaceZ's script not working on Twitch.

### ISSUE THREAD

**Issue by MegamanXtreme** [janekptacijarabaci/greasemonkey#8]
Attempting the script on Firefox(TamperMonkey and Grease Monkey) works, you can see the icon appear.
Since the add-on is now Jetpack and not installing on PaleMoon, I wanted to try the UserScript.

Direct Link to the Script: https://cdn.frankerfacez.com/script/ffz_injector.user.js
What appears when it is installed: https://i.gyazo.com/04a80d19262dc422d571f2f677876d82.png

**Comment by janekptacijarabaci** [comment]
Throws an error in Browser Console:
```
SyntaxError: class is a reserved identifier
cdn.frankerfacez.com/script/avalon.js:1:2216
```

`class` is not supported in Pale Moon, see also:
https://github.com/MoonchildProductions/Pale-Moon/issues/1243
