### ISSUE TITLE
YADG doesn't work with GM 3.30rc3

### ISSUE THREAD

**Issue by yetiisyou** [janekptacijarabaci/greasemonkey#9]
Hi All!
subj

This script use for create torrents on private trackes redacted and apollo.

after update Palemoon browser on 27.6.2х64 YADG doesn't work.

https://github.com/SavageCore/yadg-pth-userscript  author also does not know the reason =(

**Comment by janekptacijarabaci** [comment]
> on private trackers

I'm sorry then, without some debugging information I can't do anything...

**Comment by yetiisyou** [comment]
In what form do you provide this information?

**Comment by SavageCore** [comment]
The error appeared once I implemented the [GM4 polyfill](https://github.com/greasemonkey/gm4-polyfill) but I've had no luck debugging where it fails... Only `GM.xmlHttpRequest` is used.

**Comment by janekptacijarabaci** [comment]
Thank you for feedback :-)
See https://github.com/greasemonkey/gm4-polyfill/pull/9

**Comment by janekptacijarabaci** [comment]
Merged:
https://github.com/greasemonkey/gm4-polyfill/pull/9

Could you try it, please?
- `gm4-polyfill.js` - it is necessary to overwrite this require

See also:
https://github.com/MoonchildProductions/Pale-Moon/pull/1549
...but the new (unstable) version has not yet been released.

**Comment by janekptacijarabaci** [comment]
IMHO: This issue was fixed.

**Comment by yetiisyou** [comment]
Hi all
and on palemoon on 27.7.2x64 doesn't work again YADG (

**Comment by janekptacijarabaci** [comment]
Throws an error in Browser Console:
```
invalid for/in left-hand side
pth_yadg.user.js:349:7
```
=> https://github.com/SavageCore/yadg-pth-userscript/commit/622b3bd9882e960cb6020b56725b6007f90ba068:

``` javascript
for (const key in localStorage)
```

Using `for (const x in y)` ([bug 1263355](https://bugzilla.mozilla.org/show_bug.cgi?id=1263355)) in Pale Moon has not been implemented (but [UXP](https://forum.palemoon.org/viewtopic.php?f=5&t=18211#p133880) already contains it by default).

**Comment by yetiisyou** [comment]
ok. what should I do? )

**Comment by janekptacijarabaci** [comment]
> what should I do

You can wait or try use an older version than v1.4.39:
https://github.com/SavageCore/yadg-pth-userscript/blob/a4db059d53db41097216c37d3dce2aa3b51105cf/pth_yadg.user.js
